### PR TITLE
Expand tests

### PR DESCRIPTION
**Pull request by aldonunez**

### CODE REVIEW

**Comment by rainers** [comment]
Wow!

Actually I haven't built the tests for years due to the external cpptest dependency. I think we should just include it into the source tree as with other external libs. This would make it easier to run the tests with the Appveyor build, too.

Doesn't the change to FormatValue/FormatRawValue affect your testing? It causes a link failure for me.

**Comment by aldonunez** [comment]
I agree that we should do what it takes to make the tests easier to build. About FormatValue: I don't have problems linking. But, I'll take a look to see why.

**Comment by rainers** [comment]
> I agree that we should do what it takes to make the tests easier to build. 

Ok, I will add it to master.

> About FormatValue: I don't have problems linking. But, I'll take a look to see why.

It only fails to build the EEDTest. It's caused by one of my recent changes: https://github.com/rainers/mago/commit/f3a33a203f336247d7e389407e2042a2f61d7c20#diff-5f48819430306585f14a29ca2e14c5b5R18.

**Comment by rainers** [comment]
I'll merge this to fix compilation and get rid of the boost dependency, will follow up with adding cpptest.

**Comment by rainers** [comment]
@aldonunez BTW: all the tests are now building, but I have no idea how to run them successfully: EEDTest seems to need some test files, and utestExec only report 4% correct.

**Comment by aldonunez** [comment]
utestExec has expectations on the locations of files. It expects to be run from the folder where it is. Also, it expects the sample debuggees to be placed right next to utestExec.exe.

I'll look at EEDTest to make sure it's up-to-date.

**Pull request merged**
