### PR TITLE
Load Wow64*Wow64FsRedirection functions dynamically to support Windows XP

### PR DESCRIPTION
**Pull request by denis-sh**
`TRY_LOAD_WINAPI_FUNC` macro was introduced for this purpose:
```C
#define TRY_LOAD_WINAPI_FUNC(module, type, name, params) \
    typedef type (WINAPI *name ## Ptr) params; \
    name ## Ptr name = reinterpret_cast<name ## Ptr>(GetProcAddress(module, #name));
```

### CODE REVIEW

**Comment by denis-sh** [comment]
Also reopened [Issue 12565](https://issues.dlang.org/show_bug.cgi?id=12565) until this is merged and no other problems occurred.

**Comment by ZombineDev** [comment]
Btw, I think that now DMD does not support Windows XP officially, but there's harm in removing limitations such as this from VisualD.

**Comment by denis-sh** [comment]
> Btw, I think that now DMD does not support Windows XP officially, but there's harm in removing limitations such as this from VisualD.

Citing Walter's [post](http://forum.dlang.org/post/ktfgps$2ghh$1@digitalmars.com):
> As a practical matter, we do not test on XP, and so it is disingenuous to claim official support for it.
>
> I suggest saying we "officially" support Win7 or later, and unofficially support versions back to XP. Unofficially means there's code there to support it, and we accept pull requests to fix bugs in it, we will try not to break it, but we don't test or guarantee that it'll work.

**Comment by rainers** [comment]
> but there's harm in removing limitations such as this from VisualD

I guess you meant "no harm"?

**Comment by rainers** [comment]
Thanks. LGTM, T'll have to have to merge without testing on XP, though.

**Comment by denis-sh** [comment]
> Thanks. LGTM, T'll have to have to merge without testing on XP, though.

I can test if you make a binary available to download.

**Comment by rainers** [comment]
> I can test if you make a binary available to download.

You can download it here: https://gist.github.com/rainers/6cdf73b48837defb9f88/raw/7c2dcf8f07c50825887df896fe4d94d2f8cf089c/MagoNatDE.dll

Just replace the DLL in the VisualD/mago folder.

**Comment by denis-sh** [comment]
> You can download it here

Works well on Windows XP. Great, thanks.

**Pull request merged**
