### PR TITLE
Mago-MI refactoring and fixes

### PR DESCRIPTION
**Pull request by buggins**

### CODE REVIEW

**Comment by rainers** [comment]
There's a "Merge branch master" commit. I guess you should rebase this.

**Comment by buggins** [comment]
Not sure how to do it.
on my master branch, git rebase upstream/master?

**Comment by rainers** [comment]
> Not sure how to do it.
> on my master branch, git rebase upstream/master?

Sounds about right. I'm not an expert on the git command line, though. I use TortoiseGit which guides you through the process interactively.

**Comment by buggins** [comment]
did rebase
i'm not an expert, too
just hope all is ok

**Comment by rainers** [comment]
Unfortunately, it's even worse now because your commits appear twice and the merge commits are also still there. You can see these in the list of commits.

Maybe you should start with a new branch based on rainers/master (I don't like those upstream/origin terminology as it is too ambiguous) and cherry pick your commits to this.

**Comment by buggins** [comment]
See new pull request.
Closing this one,

**Pull request closed without merging**
